export enum MESSENGER_BOTTOM_TAB {
  CHAT = '[MESSENGER_BOTTOM_TAB] CHAT',
  FRIENDS = '[MESSENGER_BOTTOM_TAB] FRIENDS',
  DISCOVER = '[MESSENGER_BOTTOM_TAB] DISCOVER',
}

export enum MESSENGER_CHAT_STACK {
  LIST_MSG = '[MESSENGER_CHAT_STACK] LIST_MSG',
}
